// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CT01 - PGEDigital', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('CT01 - PGEDigital', async function() {
    await driver.get("http://10.120.100.168/paivav/pgedigital/")
    await driver.manage().window().setRect({ width: 1899, height: 1028 })
    await driver.findElement(By.id("login")).click()
    await driver.findElement(By.id("login")).sendKeys("testepgedigital")
    await driver.findElement(By.id("senha")).sendKeys("Senha1234")
    await driver.findElement(By.css(".btn-lg")).click()
    await driver.findElement(By.css("#menu_principal > .dropdown:nth-child(1) > .dropdown-toggle")).click()
    await driver.findElement(By.css("#menu_principal > li:nth-child(2) > a")).click()
    await driver.findElement(By.css(".dropdown:nth-child(4) > .dropdown-toggle")).click()
    await driver.findElement(By.css(".dropdown:nth-child(5) > .dropdown-toggle")).click()
    await driver.findElement(By.css("#menu_principal > li:nth-child(6) > a")).click()
    await driver.findElement(By.css(".dropdown:nth-child(8) > .dropdown-toggle")).click()
    await driver.findElement(By.css(".dropdown:nth-child(9) > .dropdown-toggle")).click()
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.css("#menu_principal > li:nth-child(10) > a")).click()
    vars["win4819"] = await waitForWindow(2000)
    vars["root"] = await driver.getWindowHandle()
    await driver.switchTo().window(vars["win4819"])
    await driver.switchTo().window(vars["root"])
    await driver.findElement(By.css("#menu_principal > .dropdown:nth-child(1) > .dropdown-toggle")).click()
    await driver.findElement(By.css(".open:nth-child(1) li:nth-child(1) > a")).click()
    await driver.findElement(By.css(".dropdown:nth-child(4) > .dropdown-toggle")).click()
    await driver.findElement(By.css(".dropdown:nth-child(4) li:nth-child(1) > a")).click()
    await driver.findElement(By.css(".dropdown:nth-child(5) > .dropdown-toggle")).click()
    await driver.findElement(By.css(".dropdown:nth-child(5) li:nth-child(1) > a")).click()
    await driver.findElement(By.css(".dropdown:nth-child(7) > .dropdown-toggle")).click()
    await driver.findElement(By.css(".dropdown:nth-child(7) > .dropdown-menu > li:nth-child(1) > a")).click()
    await driver.findElement(By.id("btn-cancelar")).click()
    await driver.findElement(By.css(".dropdown:nth-child(8) > .dropdown-toggle")).click()
    await driver.findElement(By.css(".dropdown:nth-child(8) > .dropdown-menu > li:nth-child(2) > a")).click()
    await driver.findElement(By.css(".btn-block")).click()
    await driver.findElement(By.css(".dropdown:nth-child(9) > .dropdown-toggle")).click()
    await driver.findElement(By.css(".dropdown li:nth-child(11) > a")).click()
    await driver.findElement(By.css("#menu_principal > li:nth-child(3) > a")).click()
  })
})
