// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert');
let fs = require('fs');
let chrome = require('selenium-webdriver/chrome');
let service = new chrome.ServiceBuilder()
     .loggingTo('C:/Users/vin_r/OneDrive/PGE/GTI/TESTES/SELENIUM/TestesJs/Log e Evidencias/LogEditarDescricao.txt')
     .enableVerboseLogging()
     .build();
     let options = new chrome.Options();

describe('Editando Título dos Docs', function() {
  this.timeout(30000)
  let driver = chrome.Driver.createSession(options, service);
  let vars
  beforeEach(async function() {
    driver = await new Builder()
    .forBrowser('chrome')
    .setChromeOptions(new chrome.Options().headless())
    .build()
    vars = {}
  })
  // afterEach(async function() {
  //   await driver.quit();
  // })
  it('Editando Título dos Docs', async function() {
    // Test name: Editando Título dos Docs
    await driver.get('http://10.120.100.168/paivav/pgedigital/caixa-entrada/index');
    await driver.getTitle();
    await driver.manage().setTimeouts({implicit: 1000});

 //LOGIN e SENHA
   let login =  driver.findElement(By.name('login'));
   let senha =  driver.findElement(By.name('senha'));
   let Button =  driver.findElement(By.className('btn btn-lg btn-primary btn-block'));

   await login.sendKeys('testepgedigital');
   await senha.sendKeys('Senha1234');
   await Button.click();
    await driver.get("http://10.120.100.168/paivav/pgedigital/processo-administrativo/editar/4036/documentos")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.id("editar_descricao_0")).click()
    await driver.findElement(By.id("editar_descricao_0")).click()
    {
      const element = await driver.findElement(By.id("editar_descricao_0"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css("#editar_descricao_0 > input")).sendKeys("Alterado1")
    await driver.findElement(By.css("#editar_descricao_0 > input")).sendKeys(Key.ENTER)
    await driver.findElement(By.id("editar_descricao_1")).click()
    await driver.findElement(By.id("editar_descricao_1")).click()
    {
      const element = await driver.findElement(By.id("editar_descricao_1"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css("#editar_descricao_1 > input")).sendKeys("Alterado2")
    await driver.findElement(By.css("#editar_descricao_1 > input")).sendKeys(Key.ENTER)
    await driver.findElement(By.id("editar_descricao_2")).click()
    await driver.findElement(By.id("editar_descricao_2")).click()
    {
      const element = await driver.findElement(By.id("editar_descricao_2"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css("#editar_descricao_2 > input")).sendKeys("Alterado3")
    await driver.findElement(By.css("#editar_descricao_2 > input")).sendKeys(Key.ENTER)
    await driver.findElement(By.id("editar_descricao_3")).click()
    await driver.findElement(By.id("editar_descricao_3")).click()
    {
      const element = await driver.findElement(By.id("editar_descricao_3"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css("#editar_descricao_3 > input")).sendKeys("Alterado4")
    await driver.findElement(By.css("#editar_descricao_3 > input")).sendKeys(Key.ENTER)
    await driver.findElement(By.id("editar_descricao_4")).click()
    await driver.findElement(By.id("editar_descricao_4")).click()
    {
      const element = await driver.findElement(By.id("editar_descricao_4"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css("#editar_descricao_4 > input")).sendKeys("Alterado5")
    await driver.findElement(By.css("#editar_descricao_4 > input")).sendKeys(Key.ENTER)
    await driver.findElement(By.id("btn-salvar")).click()
    {
      const elements = await driver.findElements(By.css("#tabelaDocumentos th:nth-child(5)"))
      assert(elements.length)
    }
    let ele = await driver.findElement(By.css("body"));
    // screenshot
    let encodedString = await ele.takeScreenshot(true);
    await fs.writeFileSync('./tests/TestCase/View/AlterarTituloDocs.png', encodedString, 'base64');
    // await fs.writeFileSync('./image.png', encodedString, 'base64');
  })
})
