// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('google', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder()
    .forBrowser('chrome')
    .build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('google', async function() {
    await driver.get("https://www.google.com/")
    await driver.findElement(By.xpath("//textarea")).click()
    await driver.findElement(By.xpath("//textarea")).click()
    await driver.findElement(By.css(".zgAlFc path")).click()
    await driver.findElement(By.xpath("//div[@id=\'searchform\']")).click()
    await driver.findElement(By.id("APjFqb")).click()
    await driver.findElement(By.id("APjFqb")).sendKeys("jenkins")
    await driver.findElement(By.css(".ly0Ckb")).click()
    {
      const element = await driver.findElement(By.linkText("Notícias"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".zgAlFc path")).click()
    await driver.findElement(By.id("APjFqb")).click()
    await driver.findElement(By.css(".zgAlFc svg")).click()
    {
      const element = await driver.findElement(By.css(".zgAlFc svg"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
  })
})
