// Generated by Selenium IDE
const { Builder, By, until } = require('selenium-webdriver');
const firefox = require('selenium-webdriver/firefox');
const assert = require('assert');

(async function firstScript() {
  let driver;

  try {
    const firefoxOptions = new firefox.Options()
      .addArguments('--headless')
      .addArguments('--disable-dev-shm-usage');
      
    driver = await new Builder()
      .forBrowser('firefox')
      .setFirefoxOptions(firefoxOptions)
      .build();
    await driver.get("http://pgedigital/")
    await driver.findElement(By.id("login")).click()
    await driver.findElement(By.id("login")).sendKeys("testepgedigital")
    console.log("Login inserido com sucesso!");
    await driver.findElement(By.id("senha")).click()
    console.log("Senha inserida com sucesso!");
    await driver.findElement(By.id("senha")).sendKeys("Senha1234")
    await driver.findElement(By.css(".btn-lg")).click()
    console.log("Login bem-sucedido!");

    // Abrir uma nova aba
    await driver.executeScript("window.open('', '_blank');");
    const abas = await driver.getAllWindowHandles();
    await driver.switchTo().window(abas[1]);
    console.log('Nova aba aberta com sucesso!');

    // Abrir URL na nova aba
    await driver.get('http://pgedigital/m-n-i/consultar-processo/01837751020238190001/TJRJ');
    console.log('Acesso ao tribunal TJRJ com sucesso!');

    await driver.executeScript("window.open('', '_blank');");
        const novasAbas = await driver.getAllWindowHandles();
        await driver.switchTo().window(novasAbas[2]);

        // Abrir URL na nova aba
        await driver.get('http://pgedigital//m-n-i/consultar-processo/50159512020234025118/JFRJ');
        console.log('Acesso ao tribunal JFRJ com sucesso!');

        await driver.executeScript("window.open('', '_blank');");
        const novasAbas2 = await driver.getAllWindowHandles();
        await driver.switchTo().window(novasAbas2[3]);

        // Abrir URL na nova aba
        await driver.get('http://pgedigital/m-n-i/consultar-processo/09693651120238190001/PJE1');
        console.log('Acesso ao tribunal PJE1 com sucesso!');

        await driver.executeScript("window.open('', '_blank');");
        const novasAbas3 = await driver.getAllWindowHandles();
        await driver.switchTo().window(novasAbas3[4]);

        // Abrir URL na nova aba
        await driver.get('http://pgedigital/m-n-i/consultar-processo/09637158020238190001/PJE223');
        console.log('Acesso ao tribunal PJE223 com sucesso!');

    // Links de outros tribunais
    // await driver.get("http://pgedigital/m-n-i/consultar-processo/00922107820231000000/STF");
    // console.log("Processo STF selecionado com sucesso!");

    // await driver.get("http://pgedigital/m-n-i/consultar-processo/00297828120228190000/STJ")
    // console.log("Processo STJ selecionado com sucesso!");

    // await driver.get("http://pgedigital//m-n-i/consultar-processo/50197137220234020000/TRF2")
    // console.log("Processo TRF2 selecionado com sucesso!");

    // await driver.get("http://pgedigital//m-n-i/consultar-processo/01009984820235010282/TRT1")
    // console.log("Processo TRT1 selecionado com sucesso!");

    // await driver.get("http://pgedigital/m-n-i/consultar-processo/01006077020225010204/TRT2")
    // console.log("Processo TRT2 selecionado com sucesso!");

    // await driver.get("http://pgedigital/m-n-i/consultar-processo/01012333020185010075/TST")
    // console.log("Processo TST selecionado com sucesso!");

    // Abrir a primeira aba
    // await driver.get('http://pgedigital/m-n-i/consultar-processo/01837751020238190001/TJRJ');
    // console.log('Aba 1 aberta com sucesso!');

    // Execute operações na primeira aba
    // ...

    // Execute operações na segunda aba
    // ...

    // Voltar para a primeira aba
    // await driver.switchTo().window(abas[0]);
    // console.log('Retornando para a aba 1');

    // Execute mais operações na primeira aba
    // ...
    console.log("Teste finalizado!");
  } catch (error) {
    console.error('Ocorreu um erro:', error);
  } finally {
    if (driver) {
      await driver.quit();
    }
  }
})();